### ISSUE TITLE
Any DP-900 Issues? 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#36]
# Module: ALL
#### Step: 00

Description of issue

Just preparing for this course. Has anyone delivered it lately? I find it hard to believe there are no Issues associated with a MOC course. 

Appreciate any insight other MCTs may have if they delivered it recently. 

Thank you

Arnold

![image](https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/assets/1082625/78f0b7dd-433d-4717-bc29-997aff0e9d9f)

**Comment by Sp3ci3s8472** [comment]
I do have an issue, not sure if that is what you are getting at? The simulation of the IOT device created by this git repo is broken for me:
`myusername [ ~/dp-900/streaming ]$ bash iotdevice.sh 
This command is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{'Message': 'ErrorCode:DeviceNotFound;iotdevice', 'ExceptionMessage': 'Tracking ID:2de925702854449686c2f5f8dec70227-G:0-TimeStamp:10/03/2023 14:12:32'}`

**Comment by Mihai-Ac** [comment]
Hello @Sp3ci3s8472 

I´ve tried reproducing the error but I couldn´t. The _iotdevice.sh_ ran without any errors for me.
Can you please check and confirm that the setup script completed successfully and the **iotinput** and **bloboutput** have been created? 
Regards,
Mihai

**Comment by Sp3ci3s8472** [comment]
I'll have to run it again. In my last attempt I can at least confirm that the iotinput and bloboutput were created. The only thing that might have been suspect is the warning I got about some resource not being linked to my account and it not working in the near future. I'm not a 100% sure on that.
I'll get back on that Mihai.

**Comment by Sp3ci3s8472** [comment]
This time I ran the setup.sh I got some errors. Not sure if I got those the first time, but I don't think so.
`bash setup.sh
Installing required Azure CLI extensions - this may take a few minutes...
The installed extension 'stream-analytics' is experimental and not covered by customer support. Please use with discretion.
Using the learn8efad8c088604f2e96 resource group...
Creating IoT hub...
Error occurred in request., RetryError: HTTPSConnectionPool(host='iothub0d632216fc054547b9.azure-devices.net', port=443): Max retries exceeded with url: /devices/iotdevice?api-version=2021-04-12 (Caused by ResponseError('too many 500 error responses'))
ERROR: {'Message': 'ErrorCode:DeviceNotFound;iotdevice', 'ExceptionMessage': 'Tracking ID:6411a510507b47d0bca8b728dc7218b3-G:0-TimeStamp:10/03/2023 17:02:03'}
Creating storage...
The public access to all blobs or containers in the storage account will be disallowed by default in the future, which means default value for --allow-blob-public-access is still null but will be equivalent to false.
Creating Stream Analytics job...
Command group 'stream-analytics' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Command group 'stream-analytics' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Command group 'stream-analytics' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Command group 'stream-analytics' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus`

**Comment by Mihai-Ac** [comment]
@arnoldvilleneuve  - this looks more like a topic for the [MCT Lounge](https://techcommunity.microsoft.com/t5/mct-lounge/ct-p/MCT-Lounge ). I found that generally these types of questions are found in the **_Community Cafe Discussions_** area.

@Sp3ci3s8472  - the warnings are normal and we will update the instructions soon to inform students about that. If you are still having issues with this, please open another issue so we can properly track it and handle it.
