### ISSUE TITLE
DP-900 Lab 05 instructions update

### ISSUE THREAD

**Issue by davidnabram** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#43]
# Module: DP-900
## Lab/Demo: 05

Description of issue
cli command uses wrong directory here: https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/blob/c0182c37f6fbfc9a503c4f06a4d36182f04459ba/Instructions/Labs/dp900-05-stream-lab.md?plain=1#L34

Update from `cd dp-900/streaming` -> `cd dp/streaming`

**Comment by rcaper** [comment]
Will review and update if needed. Thanks!

**Comment by Mihai-Ac** [comment]
Hello @davidnabram 

The previous instruction on step 3 clones the repo files into the a folder called  **dp-900**
https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/blob/c0182c37f6fbfc9a503c4f06a4d36182f04459ba/Instructions/Labs/dp900-05-stream-lab.md?plain=1#L28 

Because of that, the `cd dp-900/streaming` command is correct.
If the student/user would clone to another folder, let´s say just **dp**, then the cli command wound indeed be `cd dp/streaming`
