### ISSUE TITLE
cannot create IOThub

### ISSUE THREAD

**Issue by matony1989** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#6]
# Module: 00
#### Step: 00

Description of issue
Creating IoT hub...
(400019) Max number of Iot Hubs exceeded for sku = Free, Max Allowed = 1, Current = 2 in the subscription Id: 612c8730-55c5-4771-91d5-3de394e409be. If you contact a support representative please include this correlation identifier: 9f0867e3-6b27-4432-ac99-8cf4001055f5, timestamp: 2022-04-28 14:58:27Z, errorcode: IH400019.
Code: 400019
Message: Max number of Iot Hubs exceeded for sku = Free, Max Allowed = 1, Current = 2 in the subscription Id: 612c8730-55c5-4771-91d5-3de394e409be. If you contact a support representative please include this correlation identifier: 9f0867e3-6b27-4432-ac99-8cf4001055f5, timestamp: 2022-04-28 14:58:27Z, errorcode: IH400019.
ERROR: Unable to find IoT Hub: iothubdda7a76355d74b63a8 in current subscription 612c8730-55c5-4771-91d5-3de394e409be.
Unable to find IoT Hub: iothubdda7a76355d74b63a8 in current subscription 612c8730-55c5-4771-91d5-3de394e409be.
ERROR: Unable to find IoT Hub: iothubdda7a76355d74b63a8 in current subscription 612c8730-55c5-4771-91d5-3de394e409be.
Creating storage...
Creating Stream Analytics job...
Repro steps:

1.initiate bash setup.sh
1.
1.

**Comment by rcaper** [comment]
The easiest resolution is to [use the Sandbox subscription](https://docs.microsoft.com/learn/modules/explore-fundamentals-stream-processing/5-exercise-stream-analytics) instead of your own subscription. 

Alternatively, you could edit the setup.sh script and try changing this line:

az iot hub create --name $iothubname --resource-group $rg --sku F1 --partition-count 2 --output none

To:

az iot hub create --name $iothubname --resource-group $rg --sku S1 --partition-count 2 --output none

**Comment by matony1989** [comment]
I just checked the course and it was the sandbox. ( hard to remember which lectures have sandbox and which don´t as the sandbox is not everywhere). I tried to run the script again and it worked this time, not sure why it didn´t last time.
